Repository guiaanonima/InfoSecTools, pull requests merged in 2024-01, with the labels that each got.

#18 Criado Workflow para verificação do padrão de snake_case nos arquivos
  .github/workflows/check_snake_case.yml
  instalacao.py
  main.py
  menu.py
Labels: enhancement

#22 fix: correção ortográfica no readme.md
  README.md
Labels: bug, documentation

#23 Fix: Adição do banner nas funções
  main.py
  menu.py
Labels: bug

#24 Fix: menu()
  main.py
Labels: bug

#25 Fix: alteração do nome da variável teste
  menu.py
Labels: bug

#28 hotfix: GADEV-71 (Refatorar main.py tornando executável)
  Dockerfile
  main.py
Labels: bug

#30 hotfix/GADEV-72: criação de arquivos de utilitários
  utils.py
Labels: bug

#31 hotfix/GADEV-72: modificação de itens para utilizar o utils.py
  instalacao.py
  main.py
  menu.py
  menu_subfunctions.py
Labels: bug

#32 hotfix/GADEV-78: habilitar edição de arquivos
  menu_subfunctions.py
Labels: bug

#33 hotfix/GADEV-77: modificação na inclusão de repositórios
  __pycache__/categorias.cpython-311.pyc
  __pycache__/instalacao.cpython-311.pyc
  __pycache__/menu.cpython-311.pyc
  __pycache__/menu_subfunctions.cpython-311.pyc
  __pycache__/utils.cpython-311.pyc
  menu_subfunctions.py
Labels: bug

#34 Hotfix venv pycache
  .gitignore
  __pycache__/categorias.cpython-311.pyc
  __pycache__/instalacao.cpython-311.pyc
  __pycache__/menu.cpython-311.pyc
  __pycache__/menu_subfunctions.cpython-311.pyc
  __pycache__/utils.cpython-311.pyc
Labels: bug

#41 feat: adicionado etapa para login como root no readme
  README.md
Labels: documentation

#38 Adicionado novos pacotes não presentes no repo kali
  categorias.py
Labels: enhancement
